source = ~/BeeTuxMacro/sandbox/monitor.conf
exec-once = kitty sh ~/BeeTuxMacro/sandbox/sandbox.sh
# exec-once = kitty
general{
gaps_out = 0
gaps_in = 0
allow_tearing = true
}

decoration{
rounding = 0
blur {
enabled = false
}
shadow {
enabled = false
}
}

animations {
    enabled = false
}

render{
    new_render_scheduling = true
}
cursor{
    min_refresh_rate = 1
}
ecosystem{
    no_update_news = true
    no_donation_nag = true
}

misc{
    disable_hyprland_logo = true
    vrr = 2
    render_unfocused_fps = 5
    disable_xdg_env_checks = true
    anr_missed_pings = 3
}

bind = CTRL, M, exec, bash -c ~/BeeTuxMacro/start.sh
bind = CTRL, Q, exec, bash -c ~/BeeTuxMacro/stuff/close.sh
